export {
  createSurveyByJson,
  createAiPage,
  updateAiPage,
  AI_PAGE_MAX_HTML_LENGTH,
  AI_PAGE_MAX_TITLE_LENGTH,
  AI_PAGE_PAGE_TYPES,
  CREATABLE_SURVEY_ATYPES,
  getSurvey,
  listSurveys,
  updateSurveyStatus,
  getSurveySettings,
  updateSurveySettings,
  deleteSurvey,
  getQuestionTags,
  getTagDetails,
  clearRecycleBin,
  uploadFile,
  surveyToText,
  extractJsonlMetadata,
  normalizeJsonl,
  MAX_JSONL_SIZE,
} from "wjx-api-sdk";
export type { SurveyDetail } from "wjx-api-sdk";
